(function(){
const slots=[
{id:'cat1',service:'Catering',vendor:'Saffron & Sage',date:'Aug 22',time:'11:00 AM'},
{id:'cat2',service:'Catering',vendor:'Saffron & Sage',date:'Aug 22',time:'3:00 PM'},
{id:'photo1',service:'Photography',vendor:'Northlight Studio',date:'Aug 24',time:'2:30 PM'},
{id:'decor1',service:'Decoration',vendor:'Bloom & Beam',date:'Aug 28',time:'5:00 PM'},
{id:'venue1',service:'Venue',vendor:'The Conservatory',date:'Aug 30',time:'10:00 AM'}];
function getA(){try{return JSON.parse(localStorage.getItem('ev_appointments')||'[]')}catch(e){return []}}
function saveA(a){localStorage.setItem('ev_appointments',JSON.stringify(a))}
function status(s){return '<span class="apptStatus '+s.toLowerCase()+'">'+s+'</span>'}
function clientAppointments(){let a=getA(),booked=new Set(a.filter(x=>x.status!=='Cancelled').map(x=>x.slotId));shell('Appointments','Choose an available appointment slot and book directly with a vendor',`<div class="apptSection"><div class="apptHead"><div><span class="tag">AVAILABLE SLOTS</span><h2>Book an appointment</h2></div><p>Select a service, vendor and available time.</p></div><div class="apptSlots">${slots.map(s=>`<article class="apptCard"><div class="apptIcon">${s.service==='Catering'?'✣':s.service==='Photography'?'◉':s.service==='Decoration'?'✦':'⌂'}</div><div><h3>${s.service}</h3><p>${s.vendor}</p></div><div class="apptTime"><b>${s.date}</b><span>${s.time}</span></div>${booked.has(s.id)?'<button class="btn soft" disabled>Booked</button>':`<button class="btn dark" onclick="bookAppointment('${s.id}')">Book appointment</button>`}</article>`).join('')}</div></div><div class="apptSection"><div class="apptHead"><div><span class="tag">MY SCHEDULE</span><h2>My appointments</h2></div></div>${a.length?`<div class="apptList">${a.map(x=>`<div class="apptRow"><div><strong>${x.service}</strong><small>${x.vendor}</small></div><div><strong>${x.date}</strong><small>${x.time}</small></div><div>${status(x.status)}</div><button class="btn soft" ${x.status==='Cancelled'?'disabled':''} onclick="cancelAppointment(${x.id})">Cancel</button></div>`).join('')}</div>`:'<div class="apptEmpty">No appointments booked yet. Choose an available slot above.</div>'}</div>`)}
function vendorAppointments(){let a=getA().filter(x=>x.vendor==='Saffron & Sage');shell('Appointments','Client bookings assigned to Saffron & Sage',`<div class="apptSection"><div class="apptHead"><div><span class="tag">VENDOR SCHEDULE</span><h2>Assigned appointments</h2></div></div>${a.length?`<div class="apptList">${a.map(x=>`<div class="apptRow vendor"><div><strong>${x.client}</strong><small>${x.event}</small></div><div><strong>${x.service}</strong><small>${x.date} · ${x.time}</small></div><div>${status(x.status)}</div><button class="btn dark" ${x.status==='Cancelled'?'disabled':''} onclick="confirmAppointment(${x.id})">Confirm</button></div>`).join('')}</div>`:'<div class="apptEmpty">No client appointments assigned yet. A Catering booking from the Client portal will appear here.</div>'}</div>`)}
function adminAppointments(){let a=getA();shell('Appointments','All client appointment bookings across Eventora',`<div class="apptSection"><div class="apptHead"><div><span class="tag">ADMIN SCHEDULE</span><h2>Client bookings</h2></div><p>Client, service, vendor, date/time and current status.</p></div>${a.length?`<div class="apptList">${a.map(x=>`<div class="apptRow admin"><div><strong>${x.client}</strong><small>${x.event}</small></div><div><strong>${x.service}</strong><small>${x.vendor}</small></div><div><strong>${x.date}</strong><small>${x.time}</small></div><div>${status(x.status)}</div><button class="btn dark" ${x.status==='Cancelled'?'disabled':''} onclick="confirmAppointment(${x.id})">Confirm</button></div>`).join('')}</div>`:'<div class="apptEmpty">No client appointment bookings yet.</div>'}</div>`)}
window.bookAppointment=function(id){let s=slots.find(x=>x.id===id),a=getA();if(!s||a.some(x=>x.slotId===id&&x.status!=='Cancelled'))return;a.push({id:Date.now(),slotId:id,client:'Olivia & Noah',event:'Olivia & Noah Wedding',service:s.service,vendor:s.vendor,date:s.date,time:s.time,status:'Booked'});saveA(a);showToast('Appointment booked — Admin and Vendor can see it');clientAppointments()};
window.cancelAppointment=function(id){let a=getA(),x=a.find(y=>y.id===id);if(x)x.status='Cancelled';saveA(a);showToast('Appointment cancelled');clientAppointments()};
window.confirmAppointment=function(id){let a=getA(),x=a.find(y=>y.id===id);if(x)x.status='Confirmed';saveA(a);showToast('Appointment confirmed');role==='admin'?adminAppointments():vendorAppointments()};
const oldClient=window.renderClient,oldVendor=window.renderVendor,oldAdmin=window.renderAdmin;
window.renderClient=function(){if(activeTab==='Appointments')return clientAppointments();return oldClient()};
window.renderVendor=function(){if(activeTab==='Appointments')return vendorAppointments();return oldVendor()};
window.renderAdmin=function(){if(activeTab==='Appointments')return adminAppointments();return oldAdmin()};
})();